In [12]:
import numpy as np

In [13]:
a = np.array([[1, 6], [2, 8], [3, 11], [3, 10], [1, 7]])
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [31]:
mean_a = np.array([np.mean(a[:, 0]), np.mean(a[:, 1])])
mean_a

array([2. , 8.4])

In [32]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [42]:
a_centered_sp = np.dot(a_centered[:, 0], a_centered[:, 1])
a_centered_sp

8.0

In [41]:
a_centered_sp/a_centered.shape[0]

1.6